### ISSUE TITLE
Not working for batch request of different site from the current site

### ISSUE THREAD

**Issue by GotaloveCode** [SteveCurran/sp-rest-batch-execution#3]
Am getting bad request for requests logged from a different site than the current one.My response for the list on the current site (my.sharepoint.com/sites/ke) returns 200 OK but the rest give a 400 bad request.See the payload below:

`--batch_8890ae8a-f656-475b-a47b-d46e194fa574
Content-Type: multipart/mixed; boundary=changeset_f9c96a07-641a-4897-90ed-d285d2dbfc2e
Content-Length: 1089
Content-Transfer-Encoding: binary

--changeset_f9c96a07-641a-4897-90ed-d285d2dbfc2e--
--batch_8890ae8a-f656-475b-a47b-d46e194fa574
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

GET https://my.sharepoint.com/_api/Web/Lists/GetByTitle('Updates')/Items?$select=Id,Author/Title,Title,Description,Created&$expand=Author/Id&$filter=(Category eq 'my' or Category eq 'ALL') and Expires ge datetime'2017-10-17T03:00:53' &$orderby=Id desc HTTP/1.1
accept: application/json;odata=nometadata

--batch_8890ae8a-f656-475b-a47b-d46e194fa574
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

GET https://my.sharepoint.com/_api/web/lists/getbytitle('Announcements')/items?$select=Title HTTP/1.1
accept: application/json;odata=nometadata

--batch_8890ae8a-f656-475b-a47b-d46e194fa574
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

GET https://my.sharepoint.com/sites/ke/_api/web/lists/getbytitle('Departments')/items?$select=Title,Url&$orderby=Title HTTP/1.1
accept: application/json;odata=nometadata

--batch_8890ae8a-f656-475b-a47b-d46e194fa574--`
See the response
--batchresponse_c24c9fa5-a132-4d05-9146-f19c289224b5
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/xml;charset=utf-8

<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.Client.InvalidClientQueryException</m:code><m:message xml:lang="en-US">Invalid request.</m:message></m:error>
--batchresponse_c24c9fa5-a132-4d05-9146-f19c289224b5
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/xml;charset=utf-8

<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.Client.InvalidClientQueryException</m:code><m:message xml:lang="en-US">Invalid request.</m:message></m:error>
--batchresponse_c24c9fa5-a132-4d05-9146-f19c289224b5
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
CONTENT-TYPE: application/json;odata=nometadata;streaming=true;charset=utf-8

{"value":[{"Title":"WAREHOUSE","Url":"loadDepFrames('wh/Shared%20Documents/Forms/AllItems.aspx','WAREHOUSE')"}]}
--batchresponse_c24c9fa5-a132-4d05-9146-f19c289224b5--

**Comment by SteveCurran** [comment]
The batch operations are limited to the site url given in the RestBatchExecutor constructor. So if you need to batch operations for another site then create another RestBatchExecutor with url.

**Comment by GotaloveCode** [comment]
Thank you so much for this awesome library and for the quick response.
